clear all;close all;clc;
I = imread('lena.png');
I_gray = rgb2gray(I);
sobel_x = [-1 0 1; -2 0 2; -1 0 1];
sobel_y = [-1 -2 -1; 0 0 0; 1 2 1];
gx = imfilter(double(I_gray), sobel_x, 'same');
gy = imfilter(double(I_gray), sobel_y, 'same');
BW1 = sqrt(gx.^2 + gy.^2) > 50;
prewitt_x = [-1 0 1; -1 0 1; -1 0 1];
prewitt_y = [-1 -1 -1; 0 0 0; 1 1 1];
gx = imfilter(double(I_gray), prewitt_x, 'same');
gy = imfilter(double(I_gray), prewitt_y, 'same');
BW3 = sqrt(gx.^2 + gy.^2) > 50;
roberts_x = [1 0; 0 -1];
roberts_y = [0 1; -1 0];
gx = imfilter(double(I_gray), roberts_x, 'same');
gy = imfilter(double(I_gray), roberts_y, 'same');
BW4 = sqrt(gx.^2 + gy.^2) > 50;
sigma = 2;
size = 6*sigma;
x = -size/2:size/2;
y = x;
[X, Y] = meshgrid(x, y);
LoG = (X.^2 + Y.^2 - 2*sigma^2) .* exp(-(X.^2 + Y.^2) / (2*sigma^2));
BW5 = imfilter(double(I_gray), LoG, 'same') > 0;
BW6 = edge(I_gray, 'zerocross');
gx = imfilter(double(I_gray), sobel_x, 'same');
gy = imfilter(double(I_gray), sobel_y, 'same');
gmag = sqrt(gx.^2 + gy.^2);
BW2 = gmag > 0.1 * max(gmag(:));
BW2 = bwmorph(BW2, 'thin', Inf);
BW2 = bwareaopen(BW2, 30);
tiledlayout(2,4);
nexttile;imshow(I);
title('Original Image');
nexttile;imshow(BW1);
title('Sobel');
nexttile;imshow(BW2);
title('Canny');
nexttile;imshow(BW3);
title('Prewitt');
nexttile;imshow(BW4);
title('Roberts');
nexttile;imshow(BW5);
title('LoG');
nexttile;imshow(BW6);
title('Zero-Crossing');